version: '3'
services:
    node:
        build: .
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        environment: 
            - PORT=4000
    db:
        image: postgres
        restart: always
        build: ./database
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            - POSTGRES_PASSWORD=password
        
        