version: '3'
services:
    app:
        build: .
        command: npm run start
        volumes: 
            - ./logs:/app/logs
            - ./src:/app/src
            - /app/node_modules
        networks:
            - my-net
        restart: on-failure
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        environment: 
            PORT: ${PORT}
    db:
        image: postgres:13.3-alpine
        networks:
            - my-net
        restart: on-failure
        build: ./src/database
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: ${PGDATA}

networks:
    my-net:
        driver: bridge
        name: my-net


        
        